execute as @s[scores={qid=1}] run title @a title qwesWhat creature are creepers afraid of?
execute as @s[scores={qid=2}] run title @a title qwesWhat company is currently developing Minecraft?
execute as @s[scores={qid=3}] run title @a title qwesAn Allay can be found where?
execute as @s[scores={qid=4}] run title @a title qwesA Noteblock could affect the behaviour of...
execute as @s[scores={qid=5}] run title @a title qwesWhich of these is not an Axolotl colour?
execute as @s[scores={qid=6}] run title @a title qwesAxolotls will follow a player who holds...
